services:
  api-gateway:
    build: ./api-gateway
    restart: unless-stopped
    ports:
      - "8085:8080" # TODO: pogledaj zasto ne moze se mapirati na 8080 od hosta
    # healthcheck:
    #   interval: 10s
    #   retries: 10
    #   timeout: 30s
    #   test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"

  user-service:
    build: ./user-service
    restart: unless-stopped
    user: ${UID}:${GID}
    depends_on:
      user-service-db:
        condition: service_healthy
    environment:
      MARIADB_USER_REPOSITORY_ROOT_PASSWORD: ${MARIADB_USER_REPOSITORY_ROOT_PASSWORD}
#    ports:
#      - "8081:8081"

  user-service-db:
    image: mariadb:lts-jammy
    restart: unless-stopped
    user: ${UID}:${GID}
    environment:
      MARIADB_DATABASE: user_service_repository
      MARIADB_ROOT_PASSWORD: ${MARIADB_USER_REPOSITORY_ROOT_PASSWORD}
    volumes:
      - ./user-service-db/data:/var/lib/mysql:Z
    healthcheck:
      interval: 10s
      retries: 10
      timeout: 30s
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]