services:
  user-service:
    build: ./user-service
    restart: unless-stopped
    user: ${UID}:${GID}
    depends_on:
      user-service-db:
        condition: service_healthy
    environment:
      MARIADB_USER_REPOSITORY_ROOT_PASSWORD: ${MARIADB_USER_REPOSITORY_ROOT_PASSWORD}
    ports:
      - "8081:8081"

  user-service-db:
    image: mariadb:lts-jammy
    restart: unless-stopped
    user: ${UID}:${GID}
    environment:
      MARIADB_DATABASE: user_service_repository
      MARIADB_ROOT_PASSWORD: ${MARIADB_USER_REPOSITORY_ROOT_PASSWORD}
    volumes:
      - ./user-service-db/data:/var/lib/mysql:Z
    healthcheck:
      interval: 10s
      retries: 10
      timeout: 30s
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]