spring.application.name: learning-recommender-service

server:
  port: 8082

management:
  server:
    port: 8083
  endpoints:
    web:
      exposure:
        include: health,prometheus

learning-recommender-service:
  azure:
    api-endpoint: ${AZURE_OPENAI_ENDPOINT}
    api-key: ${AZURE_OPENAI_API_KEY}
    deployment-name: ${DEPLOYMENT_NAME}