spring.application.name: course-service
server:
  port: 8083

spring:
  sql:
    init:
      mode: always
  jackson:
    time-zone: UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mariadb://course-service-db:3306/course_service_repository
    username: root
    password: ${MARIADB_USER_REPOSITORY_ROOT_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver