global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['learning-recommender-service:8083'] # TODO: check
        labels:
          service: learning-recommender-service